gitlab-ci-multi-runner:
  image: appstery/gitlab-ci-multi-runner
  #build: .
  volumes:
    - /srv/docker/gitlab-runner:/home/gitlab_ci_multi_runner/data
  environment:
    - CI_SERVER_URL=
    - RUNNER_TOKEN=
    - RUNNER_DESCRIPTION=
    - RUNNER_EXECUTOR=shell
  restart: always
